<?php
return [
    'CargaHorariaHorasAula' => 'Carga Horária (Horas-aula)',
    'ComponentesCurriculares' => 'Componentes Curriculares',
    'Curso' => 'Curso',
    'DataAdmissao' => 'Data admissão:',
    'DataSaida' => 'Data saída:',
    'Descricao' => 'Descrição:',
    'DownloadCurriculo' => 'Download Currículo',
    'Duracao' => 'Duração:',
    'Empresa' => 'Empresa',
    'Fim' => 'Fim',
    'Inicio' => 'Início:',
    'Instituicao' => 'Instituição:',
    'Livro' => 'Livro',
    'MatrizCurricular' => 'Matriz Curricular:',
    'Nivel' => 'Nível:',
    'Plataforma' => 'Plataforma',
    'Pratica' => 'Prática',
    'Progresso' => 'Progresso:',
    'Semestre' => 'Semestre',
    'Status' => 'Status:',
    'TecnologiasUsadas' => 'Tecnologias usadas:',
    'Teoria' => 'Teoria',
    'Total' => 'Total',
];