<?php

return [
    'AntonyCharles' => 'Antony Charles',
    'AspNet' => 'Asp.Net',
    'C' => 'C#',
    'CriandoSolucoes' => 'Criando soluções através da programação.',
    'Css' => 'CSS',
    'DesenvolvimentoWeb' => 'Desenvolvedor Web!',
    'DotNet' => '.Net',
    'Html' => 'HTML',
    'HtmlCss' => 'Html e Css',
    'Java' => 'JAVA',
    'JavaScript' => 'JavaScript',
    'Laravel' => 'Laravel',
    'Mobile' => 'Mobile',
    'MySql' => 'MySql',
    'Net' => '.Net',
    'Php' => 'PHP',
    'QuemSou' => 'QUEM SOU',
    'ReactNative' => 'React Native',
    'Sql' => 'SQL',
    'SqlServer' => 'Sql Server',
    'Ssis' => 'SSIS',
    'title' => 'Antony Charles - Portfólio Desenvolvedor Web',
    'visualStudio' => 'Visual Studio',
    'Web' => 'Web',
    'Wordpress' => 'WordPress',
    'formacaoJava' => 'Formação Java (cursando)'
];